Addition of reflector CSC
lsst-ts/ts_mtreflector pull request #2
Opened 2024-06-10 23:15 UTC by JosephParsons

2024-07-17 22:37 UTC, couger01 submitted a review, later dismissed
Please add a setup.py file using one of the other repos as a template, this is still required for conda recipe version metadata.

2025-01-21 15:36 UTC, wvreeven requested changes
Looks pretty good but there is an unnecessary duplicate schema definition and I disagree with the LabjackChannel class. For the rest please review all doc strings and error messages and make sure they follow our coding guidelines.

2025-01-21 15:36 UTC, wvreeven commented on .gitignore
> +.flake8
Please remove these final 4 lines because they are already there in lines 28 to 31.

2025-01-21 15:36 UTC, wvreeven commented on COPYRIGHT
> +Copyright 2023 Association of Universities for Research in Astronomy, Inc. (AURA)
Why this change?

2025-01-21 15:36 UTC, wvreeven commented on bin/run_mtreflector
> +#!/usr/bin/env python
Please add a Vera C. Rubin  header.

2025-01-21 15:36 UTC, wvreeven commented on python/lsst/ts/mtreflector/csc.py
> +        self.reflector_controller = None
I am surprised that mypy allows this. Please add a type here so it is clear what this attribute represents.

2025-01-21 15:36 UTC, wvreeven commented on python/lsst/ts/mtreflector/csc.py
> +        create reflector controller object when enabled
Please terminate the sentence in a `.`.

2025-01-21 15:36 UTC, wvreeven commented on python/lsst/ts/mtreflector/csc.py
> +            If config is None
Please terminate this and the next sentence in a `.`.

2025-01-21 15:36 UTC, wvreeven commented on python/lsst/ts/mtreflector/csc.py
> +        This method initiates the MTReflectorController as well
Please terminate the sentence in a `.`. Check the rest of the doc strings as well. Also the messages used for errors like in line 154.

2025-01-21 15:36 UTC, wvreeven commented on tests/test_reflector.py
> +logging.basicConfig(
Please remove this config and make sure to run the unit tests locally with command line options like `--log-cli-level=DEBUG --log-format="%(asctime)s.%(msecs)03d:%(levelname)s:%(name)s:%(message)s" --log-date-format="%Y-%m-%d_%H:%M:%S"`.

2025-01-21 15:36 UTC, wvreeven commented on python/lsst/ts/mtreflector/controller.py
> +    """Class to handle opening of reflector connected to Labjack Interface
Again, please check that all sentences used anywhere end in a `.`.

2025-01-21 15:36 UTC, wvreeven commented on python/lsst/ts/mtreflector/controller.py
> +        self.labjack_item = LabjackChannel(channel=self.channel_name, status=status)
Please rename the variable to `labjack_channel` for clarity.

2025-01-21 15:36 UTC, wvreeven commented on python/lsst/ts/mtreflector/controller.py
> +        return yaml.safe_load(
This schema is an exact copy of the CSC schema. Please eliminate it here and use the one for the CSC. I think you can get rid of the entire method.

2025-01-21 15:36 UTC, wvreeven commented on python/lsst/ts/mtreflector/controller.py
> +        """
Please convert to a numpy style doc string.

2025-01-21 15:36 UTC, wvreeven commented on python/lsst/ts/mtreflector/controller.py
> +        """
Please convert to a numpy style doc string.

2025-01-21 15:36 UTC, wvreeven commented on python/lsst/ts/mtreflector/controller.py
> +        """
Please remove the newline character and start the doc string immediately following the `"""`.

2025-01-21 15:36 UTC, wvreeven commented on python/lsst/ts/mtreflector/controller.py
> +class LabjackChannel:
I don't like the implementation and use of this class. In ts_ess_labjack a similar challenge was faced and it was solved by including the channel names, offsets and scales in the config instead of deriving them here. Please adopt that solution.

2025-01-23 12:37 UTC, wvreeven requested changes
Looks a lot better. you missed a few of my earlier comments even though you indicated that you didn't. Also, please improve the code as indicated by my new comments. We're getting there!

2025-01-23 12:37 UTC, wvreeven commented on python/lsst/ts/mtreflector/controller.py
> +            await loop.run_in_executor(
There are several repetitions of this ruin_in_executor constructs to write to the LabJack. Please extract to a method with parameters and call that everywhere. I would include getting the `loop` and the error handling in that method as well.

2025-01-23 12:37 UTC, wvreeven commented on python/lsst/ts/mtreflector/csc.py
> +        This method initiates the MTReflectorController as well
I see you didn't update the doc string as I requested. Please go over all of them again and make sure that all sentences everywhere end in a `.`.

2025-01-23 12:37 UTC, wvreeven commented on python/lsst/ts/mtreflector/csc.py
> +        data : salobj.BaseMsgType
Please enclose the type in back ticks here and everywhere else.

2025-01-23 12:39 UTC, wvreeven reviewed
More comments added.

2025-01-23 12:39 UTC, wvreeven commented on python/lsst/ts/mtreflector/csc.py
> +        self.reflector_controller = None
I still don't see the type here.

2025-01-23 12:39 UTC, wvreeven commented on tests/test_reflector.py
> +logging.basicConfig(
You didn't remove the logging config.

2025-01-23 13:54 UTC, wvreeven commented on python/lsst/ts/mtreflector/csc.py
> +        self.reflector_controller = None
It does have a type.

2025-01-23 15:58 UTC, wvreeven requested changes
Looks much better. Please make sure to go to FAULT whenever a RuntimeError happens.

2025-01-23 15:58 UTC, wvreeven commented on python/lsst/ts/mtreflector/controller.py
> +    fake_value : `None` or `int`
Nitpicking. This is not an `int` but a `float`.

2025-01-23 15:58 UTC, wvreeven commented on python/lsst/ts/mtreflector/controller.py
> +        """
Please add a `Raises` block in the doc string.

2025-01-23 15:58 UTC, wvreeven commented on python/lsst/ts/mtreflector/controller.py
> +        try:
If you move the `self.log.exception` line to the `write_channel` method, you can remove the try/exception block.

2025-01-23 15:58 UTC, wvreeven commented on python/lsst/ts/mtreflector/csc.py
> +    simulation_mode : `bool`, optional
This is not a `bool` but an `int`.

2025-01-23 15:58 UTC, wvreeven commented on python/lsst/ts/mtreflector/csc.py
> +        simulation_mode: bool = False,
This is not a `bool` but an `int`.

2025-01-23 16:23 UTC, couger01 commented on python/lsst/ts/mtreflector/controller.py
> +        try:
I think I still need it for the raising the RuntimeError.

2025-01-23 17:18 UTC, wvreeven commented on python/lsst/ts/mtreflector/controller.py
> +        try:
If you
- remove the try/except block on lines 112 to 115
- raise RuntimeError in (the current) line 120
then you can get rid of the try/except in the `connect` method.

2025-01-23 17:19 UTC, wvreeven requested changes
Almost there. If we fix the `run` and `connect` methods as I indicated, we're done.

2025-01-23 17:20 UTC, wvreeven commented
Oh and the CSC still needs to go to FAULT state whenever a RuntimeError happens.

2025-01-23 18:23 UTC, wvreeven approved these changes
LGTM. Please improve that one error message as per my suggestion.

2025-01-23 18:23 UTC, wvreeven commented on python/lsst/ts/mtreflector/csc.py
> +                "CSC Tried to use reflector controller without a valid object."
Please improve this error message. Something like `Reflector controller is None.` would be much clearer.

2025-01-24 16:53 UTC, merged